apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: test-kafka-source
  namespace: default
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - test-kafka-source
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: receiver
