apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: sender
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sender
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sender
    spec:
      containers:
        - image: docker.io/aliok/kafka-src-missing-events-tests-sender
          name: sender
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: KAFKA_HOST
              value: my-cluster-kafka-bootstrap.kafka:9092
            - name: KAFKA_TOPIC
              value: test-kafka-source
            - name: SEND_DURATION
              value: '30000'  # 30 seconds
